Repository ArkEcosystem/go-client, pull requests merged in 2019-05, with the labels that each got.

#47 feat: add node/fees endpoint
  client/node.go
  client/node_requests.go
  client/node_responses.go
  client/node_test.go
Labels: Complexity: Medium, Status: Contributor Approved, Type: Feature

#49 chore: update contribution link
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#51 chore: update sdk url
  README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#52 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task
