Repository ArkEcosystem/go-client, pull requests merged in 2020-02, with the labels that each got.

#78 refactor: update models and tests
  client/blocks_responses.go
  client/blocks_test.go
  client/delegates_responses.go
  client/delegates_test.go
  client/node.go
  client/node_responses.go
  client/node_test.go
  client/peers_responses.go
  client/peers_test.go
  client/structs.go
  client/transactions_requests.go
  client/transactions_responses.go
  client/transactions_test.go
  client/votes_test.go
  client/wallets_responses.go
  client/wallets_test.go
Labels: Complexity: High, Status: Contributor Approved, Type: Refactor

#79 feat: add 2.6 endpoints
  client/bridgechain_requests.go
  client/bridgechains.go
  client/bridgechains_responses.go
  client/bridgechains_test.go
  client/businesses.go
  client/businesses_requests.go
  client/businesses_responses.go
  client/businesses_test.go
  client/client.go
  client/locks.go
  client/locks_requests.go
  client/locks_responses.go
  client/locks_test.go
  client/transactions_requests.go
  client/transactions_responses.go
  client/wallets.go
  client/wallets_test.go
Labels: Bounty: Tier 3, Complexity: Undetermined, Status: Contributor Approved, Status: Needs Review, Type: Feature

#80 release: 1.0.0
  CHANGELOG.md
Labels: Complexity: Low, Type: Release
